version: '3.8'

services:
  node-vite:
    image: node:24-alpine
    working_dir: /opt/app
    command: sh -c 'yarn --frozen-lockfile && yarn dev --host --port=3000'
    volumes:
      - ./:/opt/app
    ports:
      - "3000:3000"
    env_file:
      - ".env"
